name: Auto Update Haircut JSON

on:
  schedule:
    - cron: '0 0 * * *'  
  workflow_dispatch:     

jobs:
  build:
    runs-on: ubuntu-latest
    env:
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install google-search-results

      - name: Generate haircuts.json
        run: python generate_haircuts.py
        
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: live
